version: '3'
services:
    nginx:
        image: nginx:1.23.0
        container_name: pbit-nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./error.log:/var/log/nginx/error.log
        ports:
            - 8080:8080
        expose:
            - '8080'
        depends_on:
            - pbit-server
            - pbit-web
    pbit-server:
        build:
            context: .
            dockerfile: Dockerfile.server
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
            - ./.server.env:/usr/src/app/.env
        container_name: pbit-server
        expose:
            - '8000'
        depends_on:
            - db
    pbit-web:
        build:
            context: .
            dockerfile: Dockerfile.web
        volumes:
            - ./web:/usr/src/app
            - /usr/src/app/node_modules
        container_name: pbit-web
        expose:
            - '3000'
        depends_on:
            - pbit-server
    db:
        image: mongo
        container_name: db
        restart: always
        expose:
            - '27017'
