version: '3'
services:
    nginx:
        image: nginx:1.23.0
        container_name: nginx-prod
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./error.log:/var/log/nginx/error.log
        ports:
            - 8080:8080
        expose:
            - '8080'
        depends_on:
            - pbit-server
            - pbit-web
    pbit-server:
        build:
            context: .
            dockerfile: Dockerfile.server
        entrypoint: /usr/src/app/entrypoint.sh
        container_name: server
        expose:
            - '8000'
        depends_on:
            - db
    pbit-web:
        build:
            context: .
            dockerfile: Dockerfile.web
        entrypoint: /usr/src/app/entrypoint.sh
        container_name: web
        expose:
            - '3000'
        depends_on:
            - pbit-server
    db:
        image: mongo
        container_name: db
        restart: always
        expose:
            - '27017'
