version: "3.3"

services:
  web:
    ports:
      - 80:3000
    build:
      context: web
      dockerfile: Dockerfile
    env_file:
      - .env.web
  server:
    ports:
      - 8080:3001
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - .env.server
